version: '3'
services:
  urlshortener:
    image: application:1.0
    environment: 
      - MONGODB_CONNSTRING=mongodb://user:password@mongodb
    ports:
      - 3000:3000
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password